#!/bin/bash

cp -R ../design-system/components/Accordion ./components/.
cp -R ../design-system/components/AccordionGroup ./components/.
cp -R ../design-system/components/Autocomplete ./components/.
cp -R ../design-system/components/Avatar ./components/.
cp -R ../design-system/components/Banner ./components/.
cp -R ../design-system/components/Breadcrumbs ./components/.
cp -R ../design-system/components/Button ./components/.
cp -R ../design-system/components/Calendar ./components/.
cp -R ../design-system/components/Card ./components/.
cp -R ../design-system/components/CardIcon ./components/.
cp -R ../design-system/components/Checkbox ./components/.
cp -R ../design-system/components/CheckboxGroup ./components/.
cp -R ../design-system/components/Choice ./components/.
cp -R ../design-system/components/ChoiceToggle ./components/.
cp -R ../design-system/components/ComparisonCard ./components/.
cp -R ../design-system/components/ComparisonCardGroup ./components/.
cp -R ../design-system/components/Container ./components/.
cp -R ../design-system/components/DatePicker ./components/.
#cp -R ../design-system/components/Dialog ./components/.
cp -R ../design-system/components/Feature ./components/.
cp -R ../design-system/components/Hero ./components/.
cp -R ../design-system/components/Icons ./components/.
cp -R ../design-system/components/ImageSection ./components/.
cp -R ../design-system/components/InfoHint ./components/.
cp -R ../design-system/components/InputSlider ./components/.
cp -R ../design-system/components/Link ./components/.
#cp -R ../design-system/components/List ./components/.
cp -R ../design-system/components/Modal ./components/.
cp -R ../design-system/components/Notification ./components/.
cp -R ../design-system/components/PageTitle ./components/.
cp -R ../design-system/components/Phone ./components/.
cp -R ../design-system/components/Popover ./components/.
cp -R ../design-system/components/QuickLink ./components/.
cp -R ../design-system/components/Radio ./components/.
cp -R ../design-system/components/RadioGroup ./components/.
cp -R ../design-system/components/Select ./components/.
cp -R ../design-system/components/SelectListBox ./components/.
#cp -R ../design-system/components/SkipToContent ./components/.
cp -R ../design-system/components/Stack ./components/.
cp -R ../design-system/components/Step ./components/.
cp -R ../design-system/components/StepGroup ./components/.
cp -R ../design-system/components/Stepper ./components/.
cp -R ../design-system/components/SubmissionMessage ./components/.
cp -R ../design-system/components/Switch ./components/.
cp -R ../design-system/components/Tab ./components/.
cp -R ../design-system/components/TabPanel ./components/.
cp -R ../design-system/components/Tabs ./components/.
cp -R ../design-system/components/Textarea ./components/.
cp -R ../design-system/components/Textfield ./components/.
#cp -R ../design-system/components/Toast ./components/.
cp -R ../design-system/components/Typography ./components/.